import { useState,useEffect } from "react";
import { useParams } from "react-router-dom";
import {SERVER_URL} from '../../constants/SERVER_URL';
import logo from '../../assets/schoolLogo.webp';
import { Spinner } from "../spinner";
import {Button} from "flowbite-react";
import {jsPDF} from "jspdf";
import "jspdf-autotable";


const StudentDetails=()=>{
    const {id}=useParams();
    const [student,setStudent]=useState(null);
    const [loading,setIsLoading]=useState(true);
    const [error,setError]=useState(null);

    // download teacher data
    const downloadPDF=()=>{
        const doc=new jsPDF();
        doc.setFillColor(255,255,255);
        //header
        doc.setFontSize(18);
        doc.setFont("helvetica","bold");
        doc.text("DESTINYKERS HIGH SCHOOL",105,15,{align:"center"});

        doc.setFontSize(14);
        doc.setFont("helvetica","bold");
        doc.text("Teacher's Demographic Details",105,25,{align:"center"});
        doc.setDrawColor(150,150,150);
        doc.line(10,30,300,30);
        //content
        doc.setFontSize(12);
        doc.setFont("helvetica","normal");
        doc.text(`Name :`,10,40);
        doc.setFont("helvetica","bold");
        doc.text(`${teacher.fullName}`,40,40);

        doc.setFont("helvetica","normal");
        doc.text(`Email :`,10,50);
        doc.setFont("helvetica","bold");
        doc.text(`${teacher.email}`,40,50);

        doc.setFont("helvetica","normal");
        doc.text(`Phone No:`,10,60);
        doc.setFont("helvetica","bold");
        doc.text(`${teacher.phoneNo}`,40,60);

        doc.setFont("helvetica","normal");
        doc.text(`Sex:`,10,70);
        doc.setFont("helvetica","bold");
        doc.text(`${teacher.sex}`,40,70);

        doc.setFont("helvetica","normal");
        doc.text(`Nationality:`,10,80);
        doc.setFont("helvetica","bold");
        doc.text(`${teacher.nationality}`,40,80);

        doc.setFont("helvetica","normal");
        doc.text(`National Id:`,10,90);
        doc.setFont("helvetica","bold");
        doc.text(`${teacher.nationalId}`,40,90);

        doc.setFont("helvetica","normal");
        doc.text(`Place of Birth:`,10,100);
        doc.setFont("helvetica","bold");
        doc.text(`${teacher.placeOfBirth}`,40,100);

        doc.setFont("helvetica","normal");
        doc.text(`Box Office:`,10,110);
        doc.setFont("helvetica","bold");
        doc.text(`${teacher.boxOffice}`,40,110);

        doc.setFont("helvetica","normal");
        doc.text(`Marital Status:`,10,120);
        doc.setFont("helvetica","bold");
        doc.text(`${teacher.maritalStatus}`,40,120);

        doc.setFont("helvetica","normal");
        doc.text(`Religion:`,10,130);
        doc.setFont("helvetica","bold");
        doc.text(`${teacher.religion}`,40,130);

        doc.setFont("helvetica","normal");
        doc.text(`Role:`,10,140);
        doc.setFont("helvetica","bold");
        doc.text(`${teacher.Role}`,40,140);

        doc.setFont("helvetica","normal");
        doc.text(`Employer:`,10,150);
        doc.setFont("helvetica","bold");
        doc.text(`${teacher.Employer}`,40,150);

        doc.setFont("helvetica","normal");
        doc.text(`Date of Birth:`,10,160);
        doc.setFont("helvetica","bold");
        doc.text(`${teacher.createdAt}`,40,160);
        //footer
        doc.setFontSize(10);
        doc.setDrawColor(150,150,150);
        doc.line(10,30,300,30);
        doc.text(`Generated by SchoolSync | @ ${new Date().getFullYear()}`,105,290,{align:'center'});
        //save pdf
        doc.save(`${teacher.fullName}_demographic_Details.pdf`);
    }

    useEffect(()=>{
        const fetchStudentDetails=async()=>{
            try {
                const res=await fetch(`${SERVER_URL}/api/users/student/${id}`);
                const data=await res.json();

                if(res.ok){
                    setStudent(data);
                }else{
                    throw new Error(data.message || "Error fetching student info");
                }
            } catch (error) {
                setError(error.message)
            }finally{
                setIsLoading(false);
            };
        };
        fetchStudentDetails();
    },[id])

    if(loading) return (
        <div className="  w-80 mx-auto flex gap-4">
        <p>{<Spinner/>}</p>
        <p className="my-auto font-semibold text-cyan-700">Loading student's details...</p>
        </div>
    )
    if(error) return <p className="text-red-600 text-center font-semibold">Error fetching student's details!</p>

    return(
        <div>

            <div className="w-11/12 mx-auto bg-white">
            <div className="flex justify-center border border-cyan-300">
                <img src={logo} className="w-24 h-24"/>
                <h2 className="text-2xl font-semibold my-auto text-cyan-800">DESTINYKERS HIGH SCHOOL</h2>
            </div>
            <div>
            <p className="text-center font-semibold text-gray-900 mt-4">Student Demography</p>
            <div className="flex justify-between p-3 gap-6 w-10/12 mx-auto mt-4">
            <div>
            <ul className="flex flex-col gap-4">
                    <li>Student Name: <span className="demographyLi">{student.studentName}</span></li>
                    <li>Student Admission No: <span className="demographyLi">{student.studentAdmNo}</span></li>
                    <li>Student Class: <span className="demographyLi">{student.studentClass}</span></li>
                    <li>Place Of Birth: <span className="demographyLi">{student.placeOfBirth}</span></li> 
                    <li>Birth Date: <span className="demographyLi">{student.createdAt}</span></li>
                </ul>
            </div>
            <div>
            <ul className="flex flex-col gap-4">
            <li>Title : <span className="demographyLi">{student.parentTitle}</span></li>
            <li>Parent Name: <span className="demographyLi">{student.parentName}</span></li>
            <li>Email: <span className="demographyLi">{student.parentEmail}</span></li>
            <li>Parent Phone No: <span className="demographyLi">{student.parentPhoneNo}</span></li>
                <li>National Id No: <span className="demographyLi">{student.parentNationalId}</span></li>
            </ul>
            </div>
            <div>
            <ul className="flex flex-col gap-4">
            <li>Current Address : <span className="demographyLi">{student.parentBoxOffice}</span></li>
                <li>Religion: <span className="demographyLi">{student.religion}</span></li>
                <li>Nationality: <span className="demographyLi">{student.nationality}</span></li>
                <li>Academic Status: <span className="demographyLi">{student.status}</span></li>
            </ul>
            </div>
            </div>
            <div className="w-10/12 mx-auto pt-4 flex gap-6">
                <Button onClick={()=>(downloadPDF())}>Download</Button>
                <Button>Update</Button>
                <Button>Academic Report</Button>
                <Button>Financial Report</Button>
                <Button className="bg-red-700">Delete</Button>
            </div>
            </div>
            </div>
        </div>
    )
}

export default StudentDetails;
