const mongoose=require('mongoose')
const teacherSchema=new mongoose.Schema({
    fullName:{
        type:String,
        required:true,
        unique:true
    },
    email:{
        type:String,
        required:true,
        unique:true
    },
    phoneNo:{
        type:String,
        required:true,
        unique:true
    },
    sex:{
        type:String
    },
    placeOfBirth:{
        type:String
    },
    nationalId:{
        type:String
    },
    title:{
        type:String
    },
    nationality:{
        type:String
    },
    boxOffice:{
        type:String
    },
    maritalStatus:{
        type:String
    },
    religion:{
        type:String
    },
    Role:{
        type:String
    },
    classInCharge:{
        type:String
    },
    Employer:{
        type:String
    }
},{timestamps:true});

const Teacher=mongoose.model("Teacher",teacherSchema);
module.exports=Teacher;