const mongoose=require('mongoose')
const workerSchema=new mongoose.Schema({
    fullName:{
        type:String,
        required:true,
        unique:true
    },
    email:{
        type:String,
        required:true,
        unique:true
    },
    phoneNo:{
        type:String,
        required:true,
        unique:true
    },
    Department:{
        type:String,
        required:true,
    },
    workerId:{
        type:String,
        required:true,
        unique:true
    },
    sex:{
        type:String
    },
    placeOfBirth:{
        type:String
    },
    nationalId:{
        type:String
    },
    title:{
        type:String
    },
    nationality:{
        type:String
    },
    boxOffice:{
        type:String
    },
    maritalStatus:{
        type:String
    },
    religion:{
        type:String
    },
    status:{
        type:String
    }
},{timestamps:true});

const Worker=mongoose.model("Worker",workerSchema);
module.exports=Worker;